site/_includes/_post.njk
site/_includes/components/item.njk
site/journal/content-test.md

Add support for a 'Thanks' section.

---

site/journal/Some Thoughts on micro.blog.md

Rebase-style-merge this tomorrow morning!

Add 'Some Thoughts on micro.blog'.

---

site/_includes/components/item.njk
site/_layouts/colophon.njk
site/essays/_index.md
site/journal/_index.md
site/library/_index.md
site/pages/colophon.md
site/pages/topics.md
site/photography/_index.md
tsconfig.json

- version list counters
- colophon layout removal
- TS excludes

Polish a number of small details

---

eleventy/feed.ts
site/_includes/base.njk
site/_includes/components/atom.njk
site/_includes/feed.njk
site/atom.njk
site/feeds/appearances.11ty.js
site/feeds/appearances.njk
site/feeds/essays.11ty.js
site/feeds/essays.njk
site/feeds/journal.11ty.js
site/feeds/journal.njk
site/feeds/library.11ty.js
site/feeds/library.njk
types/eleventy.d.ts

Implement per-section feeds

---

site/journal/Writing Implements.md

Finish a post I started back in June!

Add post: 'Writing Implements'

---

site/library/Dark Matter.md

Review: Dark Matter

---

site/journal/2020/Making Illegal States Unrepresentable in TS.md

Nice post! I think you might have lost half of line 205, and meant to use Names instead of strings in the constructor calls.

fix errors in code example

---

site/journal/2020/Please Reply.md

Publish at 8am!
…it'd be nice to have scheduled posts. CMSes, yo.

Journal: short post about adding 'Reply via email'

---

site/journal/2020/Async Data and Autotracking in Ember Octane.md

Just a bit over 5,000 words with an enormous amount of code diffs along the way. 😅

Draft: Async Data and Autotracking in Ember Octane

---

site/journal/2020/Autotracking Elegant DX Via Cutting-Edge CS.md

Remove extra preposition

---

site/journal/2020/Data Constructors Part 2 Better TypeScript.md

Update Data Constructors Part 2 Better TypeScript.md

---

site/journal/2020/Autotracking Elegant DX Via Cutting-Edge CS.md

Replace invalid property access with function invocation in non-getter code example

Update Autotracking Elegant DX Via Cutting-Edge CS.md

---

site/journal/2020/Understanding args in Glimmer Components.md

Journal: Understanding `args` in Glimmer Components

---

site/journal/2020/Wrapping Up 2020 and Starting 2021.md
site/notes/2020/12/31-0959.md

Journal: 2020/2021 post

---

site/_includes/styles/components/_article.scss
site/elsewhere/Humans of Open Source.md
site/elsewhere/Keep It Local.md
site/pages/speaking/_index.md

Elsewhere: EmberConf 2021 talk materials

---

package-lock.json
package.json

Dep upgrades moar

---

site/journal/Ember Template Imports/Part 2.md

I noticed one small typo. Great article though!

Update Part 2.md

---

site/journal/Ember Template Imports/Part 1.md

Fix a few typos
I love this series!

Update Ember Template Imports Part 1

---

eleventy/config.ts
site/library/The Doctrine of Scripture/The Doctrine of Scripture.11tydata.json
site/library/The Doctrine of Scripture/_index.md
site/notes/2022/01/15-1727.md

...and a Notes post linking to it!

Library: page for The Doctrine of Scripture

---

site/journal/Ember Template Imports/Part 1.md

Is this what you meant here? 🙂

Update Part 1.md

---

site/journal/2022/Misusing TypeScript Assertion Functions for Fun and Profit.md

Update Misusing TypeScript Assertion Functions for Fun and Profit.md

---

site/_includes/styles/components/_archive-list.scss
site/_includes/styles/components/_article.scss
site/_includes/styles/components/_latest.scss
site/_includes/styles/style.scss

Trying this. I think I prefer it?

35rem, 17px max?

---

eleventy/config.ts
site/library/Thinking in Systems/Be a quality detector.md
site/library/Thinking in Systems/Thinking in Systems.11tydata.json
site/library/Thinking in Systems/_index.md

PR so I can fix it up if I messed it up. :joy:

Library: Thinking in Systems

---

site/journal/2023/Good News God does not change.md

Love the article. Saw a typo, and noticed in your footer that you welcomed fixes. Here you go! 😁

fix typo ('it' should be 'is')

---

site/essays/jj init.md

Mash the button at ~~10am~~ 11:30am!

Publish jj init essay!

---

site/essays/jj init.md

Wasn't sure what word you wanted here, so I made my own guess. ;-) :-D

Update jj init.md

---

site/notes/2025/06/History and Disposition.md

Just something I saw when reading your latest post. Thanks for sharing your thoughts.

typo: gravitate
